name: Test
run-name: "Ubuntu-22.04 :: Node 20.x :: Runtime Docker"

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

jobs:
  test:
    name: "Runner Ubuntu-22.04 LTS :: Node 20.x :: Runtime Docker"
    runs-on: ubuntu-22.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm ci --omit=optional

      - name: Run tests
        run: npm run test:ci
